### ISSUE TITLE
link to example data 

### ISSUE THREAD

**Issue by avhoeck** [BiCroLab/blissNPanalysis#1]
Hi,
I gave the tutorial a try but the link to the human example data is offline. Can you please point where I can find the 
./data/TK6_DMSO_Rep1.bed.gz
./data/TK6_DMSO_Rep2.bed.gz
./data/TK6_ETO_Rep1.bed.gz
./data/TK6_ETO_Rep2.bed.gz
files?
thanks

**Comment by fagostini** [comment]
Hi,
The data can be downloaded from the GEO repository ([GSE145598](https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE145598)), which is now reachable also using the fixed link (thank you for having spotted it).
Once downloaded, you might have to rename the files (or modify the code) as they were automatically assigned a 'GSMXXXX' prefix.
Best, Federico
